disableStartupPopups: true
os:
  edit: "/Users/norflin/main/nvim-macos-arm64/bin/nvim {{filename}}"
  editAtLine: "/Users/norflin/main/nvim-macos-arm64/bin/nvim --line={{line}} {{filename}}"
  editAtLineAndWait: "/Users/norflin/main/nvim-macos-arm64/bin/nvim --block --line={{line}} {{filename}}"
  editInTerminal: true
  openDirInEditor: "/Users/norflin/main/nvim-macos-arm64/bin/nvim {{dir}}"
gui:
  scrollHeight: 1
  scrollPastBottom: false
  sidePanelWidth: 0.25
  showRandomTip: false
  commitHashLength: 0
  commandLogSize: 3
  switchTabsWithPanelJumpKeys: true
  theme:
    inactiveBorderColor:
      - "#474d6b"
    activeBorderColor:
      - "#666b99"
    selectedLineBgColor:
      - "#33374d"
    defaultFgColor:
      - "#9ea3c0"
